n_train: 1000
n_test: 1000
num_basis: 10
instrument_strength: 1.0
instrument_discrete: true
nonlinear_g: false
noise_sd: 0.1
noise_sd_Y: 0.1
int_train: 0.5
n_reps: 1
rep_id: 1
selected_methods:
#  - "BCF"
 - "BCF-MLP-large"
 - "IMP"
 - "Causal"
 - "OLSMLP"

run_name: n_${n_train}-inst_str_${instrument_strength}-rep_id_${rep_id}

hydra:
  run:
    # Output directory:
    dir: ../results/output_data/exp-robustness/${now:%Y%m%d_%H%M%S}/${run_name}
  sweep:
    dir: ../results/output_data/exp-robustness/${now:%Y%m%d_%H%M%S}
    subdir: ${run_name}
  job:
    # Change into the run directory before executing your script
    chdir: true