n_train: 1000
n_test: 1000
int_train: 0.5
ints_test: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 3.99]
num_basis: 10
instrument_strength: 1.0
noise_sd: 0.1
seed_numpy: 1000
seed_torch: 1234
n_reps: 10
selected_methods: ["BCF-MLP"]

run_name: baseline

hydra:
  run:
    # Output directory:
    dir: outputs/exp-regularization/${now:%Y%m%d_%H%M%S}-${run_name}
  job:
    # Change into the run directory before executing your script
    chdir: true